version: "3.8"
services:
  api:
    build: ./api/
    command: /bin/sh -c "rm -f /one_plate/tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    ports:
      - "3000:3000"
    volumes:
      - ./api:/one_plate
      - ./api/vendor/bundle:/one_plate/vendor/bundle
    depends_on:
      - db
    tty: true
    stdin_open: true
  frontend:
    build: ./frontend/
    command: sh -c "cd frontend && yarn start"
    ports:
      - "8000:3000"
    volumes:
      - ./frontend:/usr/src/app
    depends_on:
      - api
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    ports:
      - "3306:3306"
    volumes:
      - db-volume:/var/lib/mysql
volumes:
  db-volume:

